kind: pipeline
name: build-and-test-amd64

platform:
  arch: amd64

steps:
- name: Build
  image: gcc
  commands:
  - apt search cmake
  - apt-get install boost 
  - cmake .
  - make
  - ./basic_fracs
