kind: pipeline
name: build-and-test-amd64

platform:
  arch: amd64

steps:
- name: Build
  image: gcc
  commands:
  - apt search g++
  - apt-get install g++ boost libboost-all-dev cmake-data cmake
  - cmake .
  - make
  - ./basic_fracs
